[package]
name = "trois_photons"
version = "0.1.0"
authors = ["Hadrien G. <knights_of_ni@gmx.com>"]

[dependencies]
num-complex = "0.2"
num-traits = "0.2"
chrono = "0.4"
nalgebra = "0.15"
error-chain = "0.12"
