[package]
name = "trois_photons"
version = "0.1.0"
authors = ["Hadrien G. <knights_of_ni@gmx.com>"]

[dependencies]
num-complex = "^0"
num-traits = "^0"
chrono = "^0"
nalgebra = "^0"
error-chain = "^0"
