# There are two kinds of continuous integration jobs in this project:
#
# - Every code submission or master push passes continuous integration on the
#   minimal supported Rust version and the current stable Rust version.
# - Two times a month, a scheduled job makes sure that the code remains
#   compatible and lint-free on upcoming Rust toolchains (beta and nightly).
#
# No caching of Rust toolchains or target directories is performed on unstable
# runs, since those runs are rare and the caches would be invalidated inbetween
# two of them (especially for nightly toolchains).

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 3,17 * *'

name: Continuous Integration

env:
  RUSTFLAGS: -D warnings

jobs:
  # Formatter output doesn't depend on cargo features, and only needs to be
  # tested on the latest supported release of each CI run.
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      # NOTE: No need to put OS and rust version in key since only one is used
      - name: Cache stable toolchain
        if: github.event_name != 'schedule'
        uses: actions/cache@v2
        with:
          path: |
            ~/.rustup/settings.toml
            ~/.rustup/toolchains/stable-*
            ~/.rustup/update-hashes/stable-*
          key: format-toolchain

      - name: Install stable toolchain
        if: github.event_name != 'schedule'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Install nightly toolchain
        if: github.event_name == 'schedule'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Check format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check


  # Clippy and rustc lints depend on cargo features. We don't care about
  # warnings on the minimum supported version, only about building and running.
  lints:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        features:
          - ''
          - f32
          - faster-evgen
          - multi-threading
          - multi-threading,faster-threading
          - no-photon-sorting
          - standard-random
          - standard-random,f32
          - standard-random,multi-threading
          - standard-random,multi-threading,faster-threading

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      # NOTE: No need to put OS and rust version in key since only one is used
      - name: Cache stable toolchain
        if: github.event_name != 'schedule'
        uses: actions/cache@v2
        with:
          path: |
            ~/.rustup/settings.toml
            ~/.rustup/toolchains/stable-*
            ~/.rustup/update-hashes/stable-*
          key: lints-toolchain

      - name: Install stable toolchain
        id: toolchain-stable
        if: github.event_name != 'schedule'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - name: Install nightly toolchain
        if: github.event_name == 'schedule'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy

      - name: Make cargo feature set hashable
        run: echo "${{ matrix.features }}" > __features.log

      - name: Cache Cargo registry and index
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
          key: alljobs-deps-features_${{ hashFiles('__features.log') }}-lock_${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            alljobs-deps-features_${{ hashFiles('__features.log') }}
            alljobs-deps

      # NOTE: No dependency on OS since only one is used
      - name: Cache stable Cargo check target directory
        if: github.event_name != 'schedule'
        uses: actions/cache@v2
        with:
          path: target
          key: lints-target-rust_${{ steps.toolchain-stable.outputs.rustc_hash }}-features_${{ hashFiles('__features.log') }}-lock_${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            lints-target-rust_${{ steps.toolchain-stable.outputs.rustc_hash }}-features_${{ hashFiles('__features.log') }}
            lints-target-rust_${{ steps.toolchain-stable.outputs.rustc_hash }}

      - name: Type-check the program
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features "${{ matrix.features }}"

      - name: Check clippy lints
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --features "${{ matrix.features }}" -- -D warnings


  # Test that 3photons runs and produces sensible output on all supported
  # combinations of rust version and features.
  run-stable:
    if: github.event_name != 'schedule'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
          - stable
          - 1.58.0  # Minimum supported Rust version
        features:
          - ''
          - f32
          - faster-evgen
          - multi-threading
          - multi-threading,faster-threading
          - no-photon-sorting
          - standard-random
          - standard-random,f32
          - standard-random,multi-threading
          - standard-random,multi-threading,faster-threading

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      # NOTE: No dependency on OS since only one is used
      - name: Cache stable toolchain
        if: github.event_name != 'schedule'
        uses: actions/cache@v2
        with:
          path: |
            ~/.rustup/settings.toml
            ~/.rustup/toolchains/${{ matrix.rust }}-*
            ~/.rustup/update-hashes/${{ matrix.rust }}-*
          key: run-toolchain-rust_${{ matrix.rust }}

      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Make cargo feature set hashable
        run: echo "${{ matrix.features }}" > __features.log

      - name: Cache Cargo registry and index
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
          key: alljobs-deps-features_${{ hashFiles('__features.log') }}-lock_${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            alljobs-deps-features_${{ hashFiles('__features.log') }}
            alljobs-deps

      # NOTE: No dependency on OS since only one is used
      - name: Cache stable Cargo run target directory
        if: github.event_name != 'schedule'
        uses: actions/cache@v2
        with:
          path: target
          key: run-target-rust_${{ steps.toolchain.outputs.rustc_hash }}-features_${{ hashFiles('__features.log') }}-lock_${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            run-target-rust_${{ steps.toolchain.outputs.rustc_hash }}-features_${{ hashFiles('__features.log') }}
            run-target-rust_${{ steps.toolchain.outputs.rustc_hash }}

      - name: Build the program
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features "${{ matrix.features }}"

      - name: Run the program
        run: ./target/release/trois_photons | tee stdout.log

      # NOTE: No dependency on OS since only one is used
      - name: Cache numdiff installation
        id: cache-numdiff
        uses: actions/cache@v2
        with:
          path: numdiff
          key: alljobs-numdiff-5.9.0

      - name: Install numdiff
        if: steps.cache-numdiff.outputs.cache-hit != 'true'
        run: |
          CI_DIR=`pwd`
          curl https://mirrors.up.pt/pub/nongnu/numdiff/numdiff-5.9.0.tar.gz | tar -xz
          cd numdiff-5.9.0
          ./configure --prefix=$CI_DIR/numdiff
          make
          make install
          cd -

      # NOTE: Tolerances needed due to some differences between CI results and
      #       local results. Could be caused by differences in libm versions?
      - name: Compare result to reference
        run: |
          case "${{ matrix.features }}" in
            "f32")
              PRECISION="-a 1.1e-8"
              ;;
            "standard-random,multi-threading,faster-threading")
              PRECISION="-a 1.1e-16"
              ;;
            *)
              PRECISION=""
              ;;
          esac
          numdiff/bin/numdiff $PRECISION -V "reference/res.data-features_${{ matrix.features }}" res.data

      - name: Check standard output
        run: |
          case "${{ matrix.features }}" in
            "f32")
              PRECISION="-r 1.9e-5"
              ;;
            *)
              PRECISION=""
              ;;
          esac
          numdiff/bin/numdiff $PRECISION -V "reference/stdout.log-features_${{ matrix.features }}" stdout.log


  # Variant of the run-stable job for unstable periodical builds
  #
  # FIXME: There should be a way to use conditional build matrices without
  #        duplicating the whole job recipe...
  #
  run-unstable:
    if: github.event_name == 'schedule'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
          - beta
          - nightly
          - 1.58.0  # MSRV (compatibility can be broken by deps updates)
        features:
          - ''
          - f32
          - faster-evgen
          - multi-threading
          - multi-threading,faster-threading
          - no-photon-sorting
          - standard-random
          - standard-random,f32
          - standard-random,multi-threading
          - standard-random,multi-threading,faster-threading

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Make cargo feature set hashable
        run: echo "${{ matrix.features }}" > __features.log

      - name: Cache Cargo registry and index
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
          key: alljobs-deps-features_${{ hashFiles('__features.log') }}-lock_${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            alljobs-deps-features_${{ hashFiles('__features.log') }}
            alljobs-deps

      - name: Build the program
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features "${{ matrix.features }}"

      - name: Run the program
        run: ./target/release/trois_photons | tee stdout.log

      # NOTE: No dependency on OS since only one is used
      - name: Cache numdiff installation
        id: cache-numdiff
        uses: actions/cache@v2
        with:
          path: numdiff
          key: alljobs-numdiff-5.9.0

      - name: Install numdiff
        if: steps.cache-numdiff.outputs.cache-hit != 'true'
        run: |
          CI_DIR=`pwd`
          curl https://mirrors.up.pt/pub/nongnu/numdiff/numdiff-5.9.0.tar.gz | tar -xz
          cd numdiff-5.9.0
          ./configure --prefix=$CI_DIR/numdiff
          make
          make install
          cd -

      # NOTE: Tolerances needed due to some differences between CI results and
      #       local results. Could be caused by differences in libm versions?
      - name: Compare result to reference
        run: |
          case "${{ matrix.features }}" in
            "f32")
              PRECISION="-a 1.1e-8"
              ;;
            "standard-random,multi-threading,faster-threading")
              PRECISION="-a 1.1e-16"
              ;;
            *)
              PRECISION=""
              ;;
          esac
          numdiff/bin/numdiff $PRECISION -V "reference/res.data-features_${{ matrix.features }}" res.data

      - name: Check standard output
        run: |
          case "${{ matrix.features }}" in
            "f32")
              PRECISION="-r 1.9e-5"
              ;;
            *)
              PRECISION=""
              ;;
          esac
          numdiff/bin/numdiff $PRECISION -V "reference/stdout.log-features_${{ matrix.features }}" stdout.log
