# Based on templates from https://github.com/actions-rs

on: [push, pull_request]

name: Main CI

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        rust:
          - stable
          # TODO: Once workflow's looking good, extract nightly+beta in a nightly.yml
          #       workflow that's run every 6 weeks
          - beta
          - nightly
          - 1.37.0  # Minimum Supported Rust Version

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache Rust toolchains
        uses: actions/cache@v1
        with:
          path: $HOME/.rustup
          key: ${{ runner.os }}-rustup

      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Cache Cargo registry
        if: ${{ matrix.rust }} != 'nightly'
        uses: actions/cache@v1
        with:
          path: $HOME/.cargo/registry
          key: ${{ runner.os }}-cargo_registry-rust_${{ steps.toolchain.rustc_hash }}-lock_${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo index
        if: ${{ matrix.rust }} != 'nightly'
        uses: actions/cache@v1
        with:
          path: $HOME/.cargo/git
          key: ${{ runner.os }}-cargo_index-rust_${{ steps.toolchain.rustc_hash }}-lock_${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo build
        if: ${{ matrix.rust }} != 'nightly'
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo_build-rust_${{ steps.toolchain.rustc_hash }}-lock_${{ hashFiles('**/Cargo.lock') }}

      - name: Type-check the program
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Check format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check clippy lints
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      # TODO: Add unit tests
      # - name: Run unit tests
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: test

      - name: Roll a build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Cache pil.mc to ease comparative studies
        uses: actions/cache@v1
        with:
          path: pil.mc
          key: pil

      # TODO: Add debug build w/ less iterations
      # TODO: Test multiple features
      # TODO: Test output with something like numdiff
      - name: Run the program
        uses: actions-rs/cargo@v1
        with:
          command: run
          args:  --release

      - name: Upload the output for manual inspection
        uses: actions/upload-artifact@v1
        with:
          name: result
          path: res.dat

      - name: Upload accumulated results for manual inspection
        uses: actions/upload-artifact@v1
        with:
          name: pil
          path: pil.mc
