# Evil twin of main.yml which checks that 3photons remains compatible with
# latest Rust developments every once in a while.
#
# NOTE: It's useless to cache the target folder on this rare workflow since it
#       would usually be invalidated by 1/how rarely the job runs and
#       2/how frequently new nightly and beta versions come out.
#
# FIXME: For now, must be manually kept in sync with main.yml

on:
  schedule:
    - cron: '0 0 1,15 * *'

name: Unstable Rust CI


jobs:
  # Formatter output doesn't depend on cargo features, and only needs to be
  # tested on nightly since we don't care about older format norms.
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Check format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check


  # Clippy and rustc lints depend on cargo features. We don't care about
  # warnings on the minimum supported version, only about building and running.
  lints:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
          - beta
          - nightly
        features:
          - ''
          - f32
          - faster-evgen
          - multi-threading
          - multi-threading,faster-threading
          - no-photon-sorting
          - standard-random
          - standard-random,f32
          - standard-random,multi-threading
          - standard-random,multi-threading,faster-threading

    env:
      RUSTFLAGS: -D warnings

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy

      - name: Make cargo feature set hashable
        run: echo "${{ matrix.features }}" > __features.log

      - name: Cache Cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: cargo-registry-features_${{ hashFiles('__features.log') }}-lock_${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-registry-features_${{ hashFiles('__features.log') }}
            cargo-registry

      - name: Cache Cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: cargo-index-features_${{ hashFiles('__features.log') }}-lock_${{ hashFiles('**/Cargo.lock') }}
          restore_keys: |
            cargo-index-features_${{ hashFiles('__features.log') }}
            cargo-index

      - name: Type-check the program
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features "${{ matrix.features }}"

      - name: Check clippy lints
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features "${{ matrix.features }}" -- -D warnings


  # Test that 3photons runs and produces sensible output on all supported
  # combinations of rust version and features.
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
          - beta
          - nightly
        features:
          - ''
          - f32
          - faster-evgen
          - multi-threading
          - multi-threading,faster-threading
          - no-photon-sorting
          - standard-random
          - standard-random,f32
          - standard-random,multi-threading
          - standard-random,multi-threading,faster-threading

    env:
      RUSTFLAGS: -D warnings

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Cache numdiff installation
        id: cache-numdiff
        uses: actions/cache@v1
        with:
          path: $HOME/numdiff
          key: numdiff-5.9.0

      - name: Install numdiff
        if: steps.cache-numdiff.outputs.cache-hit != 'true'
        run: |
          curl https://mirrors.up.pt/pub/nongnu/numdiff/numdiff-5.9.0.tar.gz | tar -xz
          cd numdiff-5.9.0
          ./configure --prefix=$HOME/numdiff
          make
          make install
          cd -

      - name: Make cargo feature set hashable
        run: echo "${{ matrix.features }}" > __features.log

      - name: Cache Cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: cargo-registry-features_${{ hashFiles('__features.log') }}-lock_${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-registry-features_${{ hashFiles('__features.log') }}
            cargo-registry

      - name: Cache Cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: cargo-index-features_${{ hashFiles('__features.log') }}-lock_${{ hashFiles('**/Cargo.lock') }}
          restore_keys: |
            cargo-index-features_${{ hashFiles('__features.log') }}
            cargo-index

      - name: Build the program
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features "${{ matrix.features }}"

      - name: Run the program
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release --features "${{ matrix.features }}"

      # NOTE: Tolerances needed due to some differences between CI results and
      #       local results. Could be caused by differences in libm versions?
      - name: Compare result to reference
        run: |
          case "${{ matrix.features }}" in
            "f32")
              PRECISION="-a 1e-8"
              ;;
            "standard-random,multi-threading,faster-threading")
              PRECISION="-a 1e-17"
              ;;
            *)
              PRECISION=""
              ;;
          esac
          $HOME/numdiff/bin/numdiff $PRECISION -V "reference/res.data-features_${{ matrix.features }}" res.data
