# Evil twin of main.yml which checks that 3photons remains compatible with
# latest Rust developments every once in a while.
#
# FIXME: For now, must be manually kept in sync with main.yml

on:
  schedule:
    - cron: '0 0 1,15 * *'

name: Unstable Rust CI

jobs:
  # TODO: Split into multiple jobs, to reduce redundancy + increase parallelism
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        rust:
          - beta
          - nightly

    env:
      RUSTFLAGS: -D warnings

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Type-check the program
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Check format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check clippy lints
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      # TODO: Add unit tests
      # - name: Run unit tests
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: test

      - name: Roll a build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      # TODO: Test multiple features
      # TODO: Test output with something like numdiff
      - name: Run the program
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release

      - name: Upload the result for manual inspection
        uses: actions/upload-artifact@v1
        with:
          name: result-${{ runner.os }}-rust_${{ matrix.rust }}
          path: res.dat
